# Generated by Django 6.0.2 on 2026-05-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_venue_profile_enhancements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venuemedia',
            options={'ordering': ['-created_at']},
        ),
    ]
