# Generated by Django 6.0.2 on 2026-05-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_profile_enhancements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicemedia',
            options={'ordering': ['-created_at']},
        ),
    ]
