# Generated by Django 6.0.2 on 2026-03-02 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('event_city', models.CharField(blank=True, max_length=100)),
                ('event_address', models.CharField(blank=True, max_length=500)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded')], default='DRAFT', max_length=30)),
                ('totals_snapshot', models.JSONField(blank=True, default=dict)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('VENUE', 'Venue'), ('SERVICE', 'Service')], max_length=20)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pricing_snapshot', models.JSONField(blank=True, default=dict)),
                ('cancellation_policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('fulfillment_status', models.CharField(choices=[('PENDING_ACCEPTANCE', 'Pending Acceptance'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('SCHEDULED', 'Scheduled'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING_ACCEPTANCE', max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('provider_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provided_items', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicelisting')),
                ('service_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicepackage')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venues.venue')),
            ],
            options={
                'indexes': [models.Index(fields=['provider_owner', 'start_at', 'end_at'], name='orders_orde_provide_f09f4b_idx')],
            },
        ),
    ]
